### ISSUE TITLE
beforeNotify doesnt work

### ISSUE THREAD

**Issue by alexey13** [honeybadger-io/honeybadger-js#1212] opened 2023-10-16 12:20 UTC
Hey guys,

I can't understand why beforeNotify doesn't work for me. Could you please look at the demo project and tell me what I am doing wrong? Thanks a lot!

## What are the steps to reproduce this issue?
demo project [https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2FApp.js](https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2Findex.js)

## What happens?
beforeNotify doesn't filter out notice from sending

## What were you expecting to happen?
if beforeNotify return false notice should not be sent 

## Any logs, error output, etc?
Open console [https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2FApp.js](https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2Findex.js)

**Comment by subzero10** [comment] 2023-10-19 06:12
Hello @alexey13, thanks for submitting an issue!

The reproducible example really helped! The reason you are seeing the message `[Honeybadger] honeybadger.js is in development mode; the following error report will be sent in production.` is because an earlier condition to check whether the error should be sent to Honeybadger has already returned `false` (checking whether we are in `isDevelopmentMode()`).

Here's how you can test your `beforeNotify` handlers in development:
- set the `reportData` setting to `true`
- set the `environment` setting to anything else than `test`, `dev` or `development`

Setting one of the above will reach your `beforeNotify` handlers.

I'm closing the ticket, but if there's anything else you want to ask/point out about this topic, feel free to re-open (or create a new issue).

**Closed by subzero10** 2023-10-19 06:12 UTC

**Comment by alexey13** [comment] 2023-10-19 19:15
Hello @subzero10,

Thank you for reply, i updated demo with instructions that you provided and result is the same. 
[https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2Findex.js](https://stackblitz.com/edit/stackblitz-starters-yr35rz?file=src%2Findex.js)
