### ISSUE TITLE
Honeybadger + UglifyJS (with webpack) issues

### ISSUE THREAD

**Issue by kellym** [honeybadger-io/honeybadger-js#88] opened 2018-01-04 22:36 UTC
Not entirely sure what's happening, but when I combine Honeybadger with UglifyJS when building with webpack, I get this error:
```
Cannot read property 'console' of undefined
```
It's in reference to `this.console` in `function log()`. I believe it's related to how the Honeybadger script replaces window.setTimeout and uses `func.apply(null, ...` -- `null` being the key issue there.

**Comment by monde** [comment] 2018-01-05 00:03
@kellym can you give some more debugging clues? I wasn't able to repo your issue. I went and hacked the example app in `uglifyjs-webpack-plugin` https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/master/examples to see if I could repo the issue you've found.

I changed the `package.json` to have the honeybadger-js dependency

```json
{
  "name": "examples",
  "scripts": {
    "build": "../node_modules/.bin/webpack"
  },
  "dependencies": {
    "honeybadger-js": "^0.5.2"
  }
}
```

and I included a minimum honeybadger reference in the example `app/index.js`

```javascript
import component from './component';

var Honeybadger = require('honeybadger-js/honeybadger');

Honeybadger.configure({});

document.body.appendChild(component());
```

and I'm able to build the project without error, and I verified the Honeybadger references are present in the build build artifacts, e.g.

```
% npm run build

> examples@ build /Users/mike/projects/lib/uglifyjs-webpack-plugin/examples
> ../node_modules/.bin/webpack

Hash: 699de43b7c80170c68ffc8978410008a20a3849a
Version: webpack 3.10.0
Child
    Hash: 699de43b7c80170c68ff
    Time: 706ms
     Asset     Size  Chunks             Chunk Names
    app.js  8.53 kB       0  [emitted]  app
       [0] ./app/index.js 164 bytes {0} [built]
       [1] ./app/component.js 173 bytes {0} [built]
        + 1 hidden module
Child
    Hash: c8978410008a20a3849a
    Time: 697ms
        Asset       Size  Chunks             Chunk Names
     first.js    8.52 kB       0  [emitted]  first
    second.js  746 bytes       1  [emitted]  second
       [0] ./app/index.js 164 bytes {0} [built]
       [1] ./app/component.js 173 bytes {0} [built]
       [3] ./another/index.js 78 bytes {1} [built]
       [4] ./another/component.js 178 bytes {1} [built]
        + 1 hidden module
```

/cc @joshuap

**Comment by kellym** [comment] 2018-01-05 03:40
Thanks for the quick response. The issue doesn't happen on configuration -- it's only when `Honeybadger.notify` is called. I'll see if I can reproduce from the bare minimum example app, too.

**Comment by monde** [comment] 2018-01-05 03:46
good to know, I'll look into it further tomorrow and try a call on `Honeybadger.notify` ... unless you can get us a PR before then 🎉

**Comment by kellym** [comment] 2018-01-05 04:21
Thanks for the help -- did some further digging and isolated the issue.

**Comment by monde** [comment] 2018-01-09 00:48
@joshuap I put this work in a branch I created to be sure Travis CI could run tests against it with correct team permissions. The change will not pass the tests in the "Windows 7,internet explorer,8.0" environment, see: https://travis-ci.org/honeybadger-io/honeybadger-js/builds/326623663

```diff
diff --git a/honeybadger.js b/honeybadger.js
index 88115d7..0279421 100644
--- a/honeybadger.js
+++ b/honeybadger.js
@@ -631,4 +631,4 @@
   });

   return factory;
-}));
+}.bind(this)));
```

How should I proceed with @kellym's work?

**Comment by monde** [comment] 2018-01-09 00:50
isolated in branch kellym-main-fn-bound-to-this

**Comment by monde** [comment] 2018-01-09 00:53
@joshuap let me google that for you 😄 :

[How to handle lack of JavaScript Object.bind() method in IE 8
Ask](https://stackoverflow.com/questions/11054511/how-to-handle-lack-of-javascript-object-bind-method-in-ie-8)

**Comment by joshuap** [comment] 2018-01-09 02:13
I’m thinking that since it sounds like this is an issue in uglify, we just close this PR and perhaps they can fix it upstream? I’d rather not add workarounds for issues which aren’t ours. Would that make sense?

**Comment by kellym** [comment] 2018-01-09 02:40
I'm going to agree with that, too. It's not a bug in the Honeybadger code, and if it's not as straightforward as adding a `.bind(this)` it's not worth trying to solve here (we're using a fork for the meantime).

**Comment by monde** [comment] 2018-01-09 23:57
closing in light of consensus

**Comment by geoffreak** [comment] 2018-02-20 02:50
I'm now running into this issue with Webpack + Uglify (uglify-es 3.x used by uglify-js-plugin). I'm seeing the same `this.console` problem reported above.

Is there a workaround or resolution for this, or can we just not use Honeybadger on our project?

**Comment by kellym** [comment] 2018-02-20 03:08
Unfortunately I’m using a fork of Honeybadger for now...

**Comment by rathboma** [comment] 2018-02-20 16:32
Hey guys,

So seems like the problem is that this library favors IE8 compatibility over uglify compatibility.

Assuming that `this` will be bound to `window` seems to be a false assumption when using webpack and uglify, so not sure why that can be considered an uglify error as mentioned.

As the solution is adding a single `bind`, there is [a polyfill](https://stackoverflow.com/questions/11054511/how-to-handle-lack-of-javascript-object-bind-method-in-ie-8) that would allow you to support both Uglify and IE8 with minimal changes. 

I know you've closed the issue, but any chance you'd consider this change?

**Comment by stympy** [comment] 2018-02-20 16:46
Yup, we'll definitely consider options to make this better for everybody.  Thanks for looking into it!

**Comment by geoffreak** [comment] 2018-02-20 16:47
Just submitted a PR for it in #92

**Closed** 2018-02-20 17:34 UTC

**Comment by stympy** [comment] 2018-02-20 17:57
This has been released as 0.5.4 and deployed to our CDN.  Thanks everybody!

**Comment by stympy** [comment] 2018-02-20 18:24
That's a work in progress... @joshuap has the credentials for that and he's on paternity leave at the moment.  As soon as he checks in or we find the post-it note with the password we'll make that happen. :)

**Comment by stympy** [comment] 2018-02-21 17:01
v0.5.4 is now on npm.  Enjoy! :)
