### ISSUE TITLE
`Too much recursion` inside honeybadger.js

### ISSUE THREAD

**Issue by afgomez** [honeybadger-io/honeybadger-js#57] opened 2017-02-13 09:11 UTC
Hi!

There was some error in Honeybadger.js that trigger some error in Honeybadger.js that trigger some error in Honeybadger.js that...

We have four instances from this error, all coming from Firefox 51. The library where the error comes from is https://www.npmjs.com/package/react-sortablejs.

An screenshot with the error, and the line inside honeybadger recursing.

![screen shot 2017-02-13 at 09 59 12](https://cloud.githubusercontent.com/assets/57448/22877000/a6be5d8a-f1d3-11e6-8777-7eed1b9971a7.png)

Thanks a lot :)

**Comment by joshuap** [comment] 2017-02-13 17:27
Hi @afgomez, are you explicitly using `Honeybadger.wrap` anywhere in your app? That's what is causing the multiple honeybadger.js:356 locations in your stack. We also do some automatic instrumentation which uses `wrap` to automatically wrap event handlers and `setTimeout`, so if you're not using the wrap function yourself then it's likely being applied by the instrumentation.

The reason I ask is that I tested wrapping the same function multiple times and was able to produce a very similar stack trace, for instance:

```js
var w = Honeybadger.wrap;
var f = function() { throw new Error('oops'); }
var wrapped = w(w(w(w(w(f)))));
wrapped();
```

Note that to reproduce that in the console you would also need to set `Honeybadger.onerror = false;`.

My suspicion is that somewhere a function is being recursively wrapped in `Honeybadger.wrap` (or maybe even an event handler is calling itself), which would produce a stack trace like the one you're seeing. It's also possible that the "too much recursion" error that you're getting is misleading in this case -- it could still be an issue with sortable.js. I'm not saying that for sure, but I don't want to rule it out just yet.

**Comment by joshuap** [comment] 2017-04-20 17:51
Closing this for now. Let me know if you still find it a problem.

**Closed** 2017-05-23 15:39 UTC
