### ISSUE TITLE
Honeybadger causing Vue3 app to freeze

### ISSUE THREAD

**Issue by ssickles** [honeybadger-io/honeybadger-js#551] opened 2021-03-11 21:56 UTC
## What are the steps to reproduce this issue?
1. Create a vue3 application from scratch. (I used typescript but I'm not sure that is relevant)
2. Add honeybadger to my project and import it into the main.ts file for my vue app.
`import Honeybadger from '@honeybadger-io/js'`
3. Configure the api key using:
`
Honeybadger.configure({
    apiKey: ac.honeybadgerApiKey
  })
`
4. Add a line of code to notify honeybadger when an api call fails through axios.
`
    (error: AxiosError) => {
        Honeybadger.notify(error)
`

## What happens?
As long as the code compiles, then a notification gets sent to honeybadger. This part is working fine.

However, the problem occurs whenever you are making changes to your code. In this scenario I am using the base vue-cli setup with hot reloading. If I am working on building out a page and forget to return a variable from your Vue component setup function that is referenced in the template, the browser will freeze . Normally you would just see the error and go about fixing the mistake. Once corrected, it will normally refresh the page and continue working.

As soon as I add Honeybadger, what happens instead is that the browser freezes and the only way to recover is close out of the browser.

## What were you expecting to happen?
I was expecting that the hot reloading experience wouldn't change. I wasn't expecting the browser to freeze.

## Any logs, error output, etc?
When this happens I don't believe there is any output because its just frozen.

## What versions are you using?
**Operating System:** MacOS Mojave 10.14.6
**Package Version:** 3.1.0
**Browser Version:** Chrome Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by joshuap** [comment] 2021-03-11 23:13
@ssickles to confirm, you are using *@honeybadger-io/js* package in a Vue 3 app, but you're not using our [*@honeybadger-io/vue* integration package](https://docs.honeybadger.io/lib/javascript/integration/vue.html), right?

We should be looking at Vue 3 support in the near future ([see this issue](https://github.com/honeybadger-io/honeybadger-vue/issues/779)), so maybe we can also take  a look at this issue then. It does seem odd that the browser would freeze because of Honeybadger. We don't integrate with Vue specifically unless you use the *@honeybadger-io/vue* package.

/cc @incredimike

**Comment by ssickles** [comment] 2021-03-12 00:18
@joshuap Yes, this issue is occurring with @honeybadger-io/js. I started off using the @honeybadger-io/vue package but I couldn't get it to work with typescript. So, I figured I would just simplify things and use the /js package.

**Comment by joshuap** [comment] 2021-03-12 02:05
@ssickles thanks for the extra info; we'll take a look!

**Comment by joshuap** [comment] 2021-03-23 20:48
Assigning @incredimike since you're already looking into Vue 3 on https://github.com/honeybadger-io/honeybadger-vue/issues/779

**Comment by subzero10** [comment] 2021-09-09 11:45
@joshuap I will take this ticket and check it against our latest work on Vue 3.

**Comment by subzero10** [comment] 2021-09-22 11:31
Hello @ssickles,

Please note that we have officially released a version that supports vue3. You can find more about that on our [docs](https://docs.honeybadger.io/lib/javascript/integration/vue3/). Please give it a try and let us know if you have any issues!

In any case, I'm trying to reproduce the issue you are experiencing but I'm having some trouble.
I know it's been some time since you worked on this, so it may be that this has already been resolved with previous releases.
- I used vue-cli to create a fresh Vue-Typescript project with vue-class-component style.
- I installed `@honeybadger-io/vue@next`. I imported core Honeybadger to match your implementation (I did not use the Honeybadger's vue component). 
- I added an axios interceptor to catch all axios errors.

This is what my `main.ts` file looks like:
```javascript
const honeybadgerClient = Honeybadger.configure({ apiKey: "TEST" });
axios.interceptors.response.use(
  function (response) {
    return response;
  },
  function (error) {
    console.warn("global interceptor", error);
    honeybadgerClient.notify(error);
    return Promise.reject(error);
  }
);
```

I then created a component that makes a failing request using axios. The error is reported to axios.
I'm now stuck here:
> If I am working on building out a page and forget to return a variable from your Vue component setup function that is referenced in the template, the browser will freeze.

Can you please elaborate? Can you share some code that makes the browser freeze? Specifically, I don't follow what you mean with this: "forget to return a variable from your Vue component setup function that is referenced in the template".

Thanks!

cc @joshuap

**Comment by ssickles** [comment] 2021-09-22 14:03
Hey Pangratios,

This is good news. I am currently away but I will be able to take a look at
this early next week.

Scott

**Comment by ssickles** [comment] 2021-09-28 14:56
Hey Pangratios,

I created a new project to try and re-create the issue I was having with
the browser freezing. At the moment I am unable to reproduce on the newer
versions of @honeybadger-io/js. This may be fixed. I'll keep working on
trying to reproduce but good so far.

Regards,
Scott

**Comment by subzero10** [comment] 2021-09-28 16:20
@ssickles Thanks for giving it another go.
I'm happy to hear the issue is not happening for you anymore.

Please let us know if you manage to reproduce.

Thanks again!

**Closed** 2021-09-28 16:20 UTC
Labels: bug, help wanted
