### ISSUE TITLE
Receiving undefined variable errors

### ISSUE THREAD

**Issue by HolixSF** [honeybadger-io/honeybadger-js#70] opened 2017-06-01 00:22 UTC
**context**: spa static react app using webpack

When importing as a module, any function calls to the instance throws an undefined error in multiple places. I had previously created an issue(#68) where this initially started but it ended up throwing a chain of errors.

I am not sure if this is due to our build process or if it is due to source. I created a PR(#69) that ended up fixing our use case. If it can be taken a looked at to verify the root cause, it would be appreciated as my team is relying on this for our current project.

It would also be worth noting that running the test suite results in
```
Running PhantomJS...ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.
```
I have not looked into this yet and is out of scope for this, though I suspect it could be due to `grunt`.

**Comment by HolixSF** [comment] 2017-06-01 16:58
**UPDATE**

Upon further investigation we found the cause to be in the babel configuration. 
Specifically in the [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) plugin.
We are using the `es2015` preset which includes this plugin. In the babel documentation, the `strict` option defaults to false. Not sure if the preset enforces different options from the default configuration but setting the `strict` option to false resolved our issues.

PR #69 can be closed, although if the changes are non breaking it could be worth keeping as I think polluting the global namespace with those variables might not be a good idea.

**Comment by joshuap** [comment] 2017-06-20 17:22
Hey @HolixSF, I was on vacation the past couple weeks, so sorry for not getting back to you sooner. I'm glad you were able to discover a solution to this issue. I agree that there's still something potentially wrong here on our end. I'm going to dig into this and see if I can make some improvements. I'll let you know how it goes. Thanks!

**Comment by joshuap** [comment] 2017-06-30 19:53
@HolixSF I merged your PR, thanks again. I've created #73 for the test suite errors and plan to look into those soon. I suspect the issue is outdated dependencies. I'll close this issue; let me know if you run into any other problems!

**Closed by joshuap** 2017-06-30 19:53 UTC

**Comment by HolixSF** [comment] 2017-06-30 20:18
@joshuap thanks for taking a look!
